name: main
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v3.0.0

  tests:
    name: "python${{ matrix.version }} tests-${{ matrix.tests }}"
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
        tests: ["small", "large"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install jobsim
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: run small-tests
        run: poetry run pytest -s -v --junitxml=${{ matrix.tests }}_report_${{ matrix.version }}.xml tests/small
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.tests }}_report_${{ matrix.version }}
          path: ${{ matrix.tests }}_report_${{ matrix.version }}.xml


  report_workflow:
    if: always()
    runs-on: ubuntu-latest
    needs: 
      - tests
    steps:
      - uses: uoboda-splunk/workflow-info-splunk-upload-action@v1.0
        with:
          splunk_host: ${{ secrets.SPLUNK_HOST }}
          splunk_token: ${{ secrets.SPLUNK_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
