name: main
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v3.0.0

  tests:
    name: "python${{ matrix.version }} tests-${{ matrix.tests }}"
    strategy:
      fail-fast: false
      matrix:
        version: ["3.9", "3.10", "3.11"]
        tests: ["small", "large"]
        exclude:
          - version: "3.11"
            tests: "large"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install jobsim
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: run small-tests
        run: poetry run pytest -s -v --junitxml=${{ matrix.tests }}_report_${{ matrix.version }}.xml tests/${{ matrix.tests }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.tests }}_report_${{ matrix.version }}
          path: ${{ matrix.tests }}_report_${{ matrix.version }}.xml


  report_workflow:
    if: always()
    runs-on: ubuntu-latest
    needs: 
      - tests
    steps:
      - uses: uoboda-splunk/workflow-info-splunk-upload-action@v1.0
        with:
          splunk_host: ${{ secrets.SPLUNK_HOST }}
          splunk_token: ${{ secrets.SPLUNK_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Semantic release
        id: semantic
        uses: splunk/semantic-release-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @google/semantic-release-replace-plugin

