name: repo-monitor

on:
  push:
    branches:
      - "**"
      

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  call-workflow:
    uses: mbruzda-splunk/gh-monitor-workflow/.github/workflows/monitor.yml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}